themoviedb:
  url: http://localhost:8080
  apiVersion: 3
  apiToken: ${THEMOVIEDB_TOKEN}

server:
  port: 9000

selenium:
  node:
    url: http://localhost:4444/wd/hub

learngineui:
  domain: http://localhost:3000