themoviedb:
  url: https://api.themoviedb.org
  apiVersion: 4
  apiToken: ${THEMOVIEDB_TOKEN}

server:
  port: 9000

selenium:
  node:
    url: http://localhost:4444/wd/hub

learngineui:
  domain: http://localhost:3000

streaming:
  fivemovies:
    enabled: false
    url: https://5movies.cloud
  isubsmovies:
    enabled: true
    url: https://isubsmovies.com
  solarmovie:
    enabled: true
    url: https://solarmoviefree.ac
  filmfra:
    enabled: true
    url: http://filmfra.com
  altadefinizione:
    enabled: true
    url: https://altadefinizione.style
  animealtadefinizione:
    enabled: true
    url: https://www.animealtadefinizione.it
