themoviedb:
  url: https://api.themoviedb.org
  apiTokenV3: ${THEMOVIEDB_TOKEN_V3}
  apiTokenV4: ${THEMOVIEDB_TOKEN_V4}

server:
  port: 9000

selenium:
  node:
    url: http://localhost:4444/wd/hub

streaming:
  fivemovies:
    enabled: false
    url: https://5movies.cloud
  isubsmovies:
    enabled: true
    url: https://isubsmovies.com
  solarmovie:
    enabled: false
    url: https://solarmoviefree.ac
  filmfra:
    enabled: true
    url: http://filmfra.com
  altadefinizione:
    enabled: true
    url: https://altadefinizione.studio
  animealtadefinizione:
    enabled: true
    url: https://www.animealtadefinizione.it
